proxies:
  - {name: vless-reality-2, server: 104.224.152.243, port: 443, type: vless, uuid: 52fee28b-37e4-4787-be2a-c4860b501506, tls: true, flow: xtls-rprx-vision, reality-opts: {public-key: wgha8uLZhwl0EpTItVi0YMbNYttBqeS822nothwFDAI}, servername: statici.icloud.com, client-fingerprint: chrome, network: tcp}
