name: OpenClash Auto Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # 北京时间凌晨2点 = UTC 18点

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y curl python3

      - name: Clean folders
        run: |
          rm -rf rules-src-provisional
          rm -rf rules
          mkdir -p rules-src-provisional
          mkdir -p rules
          mkdir -p build

      - name: Run merge script
        run: |
          chmod +x scripts/merge.sh
          bash -x scripts/merge.sh


      - name: Build YAML
        run: |
          python3 scripts/build_yaml.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto build OpenClash rules" || echo "No changes"
          git push
